language: groovy

jdk:
  - oraclejdk8

before_install:
  # Windows development makes it hard to keep this in git.
  - chmod +x ./gradlew


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

deploy:
  provider: script
  script: ./gradlew publishPlugins
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change