language: groovy

jdk:
  - oraclejdk8

install:
#  Just in case..
  - chmod +x ./gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: change