version: "{branch} {build}"

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\.m2

branches:
  only:
  - master

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'

    settings:
      on_build_status_changed: true
      on_build_failure: true